---

# Dotfile
configure_dotfiles: false

# Homebrew
homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

homebrew_installed_packages:
  - zoxide
  - ssh-copy-id
  - espanso
  - p7zip
  - task
  - ruby
  - gnupg

homebrew_uninstalled_packages: []

homebrew_upgrade_all_packages: false

homebrew_taps:
  - homebrew/core
  - federico-terzi/espanso

homebrew_cask_apps:
  - docker
  - iterm2
  - android-sdk
  - jetbrains-toolbox
  - dropbox
  - obsidian
  - slack
  - brave-browser
  - sublime-text
  - tor-browser
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - alfred
  - kap
  - google-drive
  - google-cloud-sdk
  - telegram
  - pritunl
  - rectangle

homebrew_cask_uninstalled_apps: []

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: false

# Set this to your account password if casks need elevated privileges.
# ansible_become_password: ''

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'

homebrew_clear_cache: false

homebrew_folders_base:
  - Cellar
  - Homebrew
  - Frameworks
  - Caskroom
  - bin
  - etc
  - include
  - lib
  - opt
  - sbin
  - share
  - share/zsh
  - share/zsh/site-functions
  - var

homebrew_folders_additional: []

# Jenv
jenv_root: ~/.jenv
jenv_default_jdk: 11
jenv_jdks:
  - version: zulu-jdk11
  - version: zulu-jdk8

#
# Git repositories
#
git_repo_parent: ~/repositories
git_repo_list:
  - {repo: git@github.com:TechIsFun/template-android-library.git, local_dir: template-android-library, branch: main}
git_remove_repo_list: []

#
# SSH Hosts
#
ssh_hosts:
  - {host: myserver, user: myuser, hostname: myserver.local, identity_file: ~/.ssh/id_rsa}

#
# Crontab
#
crontab_unwanted_entries: []
crontab_daily_entries:
  - {name: "Remove all images which are not used by existing containers", job: "/usr/local/bin/docker image prune -a -f"}
crontab_weekly_entries:
  - {name: "Cleaup Xcode device data", job: "/usr/bin/xcrun simctl delete unavailable"}
crontab_entries_log: "> /tmp/crontab.log 2> /tmp/crontab_err.log"
