---
- hosts: all

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/ansible-private-config.yml"
      tags: ['always']

  tasks:
    # - import_tasks: tasks/ohmyzsh.yml
    #  tags: ['zsh']

    - import_tasks: tasks/python.yml
      tags:
        - python

    - import_tasks: tasks/npm.yml
      tags: ['npm']

    - import_tasks: tasks/jenv.yml
      tags: ['java', 'android', 'flutter']

    # - import_tasks: tasks/aws.yml
    #  tags: ['aws']

    - import_tasks: tasks/android.yml
      tags: ['android', 'flutter']

    - import_tasks: tasks/flutter.yml
      tags: ['flutter']

    # - import_tasks: tasks/one_password.yml

    - import_tasks: tasks/dock.yml
      tags: ['osx']

    - import_tasks: tasks/time-machine.yml
      tags: ['osx']
      become: false

    - import_tasks: tasks/osx-spotlight.yml
      tags: ['osx-spotlight']

    # - name: Install Vundle
    #  git:
    #    repo: https://github.com/VundleVim/Vundle.vim.git
    #    version: master
    #    dest: ~/.vim/bundle/Vundle.vim
    #    depth: 1
    #  tags: ['dotfiles']

    # - name: Install Vundle Plugins
    #  command: vim +PluginInstall +qall
    #  changed_when: false
    #  tags: ['dotfiles']

    # - name: Run .osx dotfiles.
    #  shell: ~/.osx --no-restart
    #  changed_when: false
    #  tags: ['osx']

    - import_tasks: tasks/ssh.yml
      tags: ['ssh', 'repos']

    - import_tasks: tasks/git-repos.yml
      tags: ['repos']

    - import_tasks: tasks/go.yml
      tags: ['go']

    - import_tasks: tasks/organize.yml
      tags: ['organize']

    - import_tasks: tasks/crontab.yml
      tags: ['crontab']

  handlers:
    - include: handlers/homebrew.yml
    - include: handlers/espanso.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
