---

- name: Ensure ~/.android folder exists
  file:
    path: ~/.android
    state: directory
  ignore_errors: true
  tags: ['android']

- name: Ensure ~/.android/repositories.cfg exists
  copy:
    content: ""
    dest: ~/.android/repositories.cfg
  ignore_errors: true
  tags: ['android']

# Clone Android sample app repo and check that app can be built
- name: Clone architecture-samples repo.
  git:
    repo: https://github.com/android/architecture-samples.git
    version: master
    dest: android-architecture-samples
    update: false
    depth: 1
  when: android_compile_sample_app
  tags: ['android']

- name: Ensure JDK 11 is set to make gradle work
  ansible.builtin.shell: |
    jenv versions
    jenv local 11.0
  args:
    chdir: android-architecture-samples
    creates: .java-version
  when: android_compile_sample_app
  tags: ['android']

- name: Ensure that Android app can be compiled
  ansible.builtin.command: ./gradlew assembleDebug
  args:
    chdir: android-architecture-samples
  changed_when: false
  # args:
  #  creates: "/Users/{{ ansible_user_id }}/android-architecture-samples/app/build/outputs/apk"
  when: android_compile_sample_app
  tags: ['android']
