---

- name: Ensure JDK 1.8 is set to make sdkmanager work
  command: jenv local 1.8
  args:
    chdir: android-architecture-samples
    creates: .java-version
  tags: ['android']

- name: Update Android SDK
  command: sdkmanager --update
  changed_when: false
  check_mode: false
  tags: ['android']

# Clone Android sample app repo and check that app can be built
- name: Clone architecture-samples repo.
  git:
    repo: https://github.com/android/architecture-samples.git
    version: master
    dest: android-architecture-samples
    update: false
    depth: 1
  tags: ['android']

- name: Ensure JDK 11 is set to make gradle work
  command: jenv local 11.0.15
  args:
    chdir: android-architecture-samples
    creates: .java-version
  tags: ['android']

- name: Ensure that Android app can be compiled
  ansible.builtin.command: ./gradlew assembleDebug
  args:
    chdir: android-architecture-samples
  changed_when: false
  # args:
  #  creates: "/Users/{{ ansible_user_id }}/android-architecture-samples/app/build/outputs/apk"
  tags: ['android']
