---

- name: Update Android SDK
  command: sdkmanager --update
  changed_when: false
  check_mode: false
  tags: ['android']

# Clone Android sample app repo and check that app can be built
- name: Clone architecture-samples repo.
  git:
    repo: https://github.com/android/architecture-samples.git
    version: master
    dest: android-architecture-samples
    update: false
    depth: 1
  tags: ['android']

- name: Ensure JDK is set
  command: jenv local 15.0
  args:
    chdir: android-architecture-samples
    creates: .java-version

- name: Ensure that Android app can be compiled
  command: ./gradlew assembleDebug
  args:
    chdir: android-architecture-samples
  changed_when: false
  # args:
  #  creates: "/Users/{{ ansible_user_id }}/android-architecture-samples/app/build/outputs/apk"
  tags: ['android']
