---

- name: Ensure PATH is set
  ansible.builtin.cron:
    name: PATH
    env: true
    job: "/usr/bin:/bin:/usr/local/bin"

- name: Ensure HOMEBREW_NO_CLEANUP_FORMULAE is set
  ansible.builtin.cron:
    name: HOMEBREW_NO_CLEANUP_FORMULAE
    env: true
    job: "{{ homebrew_installed_packages | join(',') }}"

- name: Ensure unwanted crontab entries are removed
  cron:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ crontab_unwanted_entries }}"

- name: Ensure daily crontab entries are set
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    special_time: daily
  with_items: "{{ crontab_daily_entries }}"

- name: Ensure weekly crontab entries are set
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    special_time: weekly
  with_items: "{{ crontab_weekly_entries }}"

- name: Ensure 5 minutes crontab entries are set
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "*/5"
  with_items: "{{ crontab_every_five_minutes_entries }}"
