---
- name: Ensure pre-commit is installed when required
  block:
  - name: Check if .pre-commit-config.yaml exists
    ansible.builtin.stat:
      path: "{{ git_repo_parent }}/{{ item.local_dir }}/.pre-commit-config.yaml"
    register: file
  - name: Ensure pre-commit is installed when .pre-commit-config.yaml exists
    command: pre-commit install
    args:
      chdir: "{{ git_repo_parent }}/{{ item.local_dir }}"
    when: file.stat.exists
    changed_when: false
