---

- name: Ensure go/bin is present
  ansible.builtin.file:
    path: "{{ go_bin_path }}"
    state: directory

- name: Ensure go packages are installed
  ansible.builtin.command: go install "{{ item.package }}"
  args:
    creates: "{{ go_bin_path }}/{{ item.bin }}"
  with_items: "{{ go_packages }}"

- name: Ensure unwanted go packages are removed
  ansible.builtin.file:
    path: "{{ go_bin_path }}/{{ item.bin }}"
    state: absent
  with_items: "{{ go_unwanted_packages }}"
