---
# https://github.com/EiyuuZack/ansible-role-jenv

- name: Ensure zulu jdk tap is tapped
  community.general.homebrew_tap:
    name: mdogan/zulu
    state: present

- name: Ensure jenv is installed
  community.general.homebrew:
    name: jenv
    state: present

- name: 'Ensure {{ jenv_root }} directory is created'
  file:
    path: "{{ jenv_root }}"
    state: directory
    mode: 0755

- name: 'Ensure {{ jenv_root }}/versions directory is created'
  file:
    path: "{{ jenv_root }}/versions"
    state: directory
    mode: 0755

- name: Ensure JDKs are installed
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ jenv_jdks }}"

- name: Get available JDKs
  command: ls -1 /Library/Java/JavaVirtualMachines/
  register: jdks
  ignore_errors: true
  changed_when: false

- name: Print list of available JDKs
  debug:
    var: jdks
    verbosity: 1

- name: Ensure JDKs are registered
  command: "jenv add /Library/Java/JavaVirtualMachines/{{ item }}/Contents/Home"
  with_items: "{{ jdks.stdout_lines }}"
  ignore_errors: true
  register: result
  changed_when: "'already' not in result.stdout"
  failed_when: "result.rc != 0 and 'already' not in result.stdout"

- name: Ensure shims are updated
  command: jenv rehash
  changed_when: false

- name: "Ensure JDK {{ jenv_default_jdk }} is default"
  command: "jenv global {{ jenv_default_jdk|quote }}"
  changed_when: false

- name: Ensure bash_profile/zshrc exists
  command: "touch /Users/{{ ansible_user_id }}/{{ item }}"
  args:
    creates: "/Users/{{ ansible_user_id }}/{{ item }}"
  with_items:
    - ".bash_profile"
    - ".zshrc"

- name: Ensure jenv PATH is set
  lineinfile:
    path: "/Users/{{ ansible_user_id }}/{{ item }}"
    line: 'export PATH="$HOME/.jenv/bin:$PATH"'
  with_items:
    - ".bash_profile"
    - ".zshrc"

- name: Ensure jenv is initialized
  lineinfile:
    path: "/Users/{{ ansible_user_id }}/{{ item }}"
    line: 'eval "$(jenv init -)"'
  with_items:
    - ".bash_profile"
    - ".zshrc"

- name: Ensure JAVA_HOME is exposed automatically
  shell: $SHELL -lc "source /Users/{{ ansible_user_id }}/.bash_profile && jenv enable-plugin export"
  changed_when: false
