---

- name: Ensure spolight exclusions are configured
  ansible.builtin.shell: |
    if grep -q "{{ item }}" "/System/Volumes/Data/.Spotlight-V100/VolumeConfiguration.plist"; then
      echo {{ item }} already configured
    else
      /usr/libexec/PlistBuddy -c "Add :Exclusions: string {{ item }}" /System/Volumes/Data/.Spotlight-V100/VolumeConfiguration.plist
    fi
  become: true
  changed_when: false
  when: ansible_os_family == "Darwin"
  loop:
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/fvm"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.gradle"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.m2"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.dart"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.dartServer"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/Library/Caches"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/Library/Containers"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.konan"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.npm"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.cache"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.pub-cache"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.cocoapods"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.bundle"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.dropbox"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.vagrant.d"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.gnupg"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.docker"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.doppler"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.fastlane"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.aws"
