---

# Source: https://github.com/geerlingguy/ansible-role-pip/blob/master/tasks/main.yml
- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop: "{{ pip_install_packages }}"
